# Generated by Django 5.1 on 2024-08-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instakilogram_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header',
            new_name='title',
        ),
    ]
